export const types = {
  GET_NEWS: "GET_NEWS",
  GET_NEWS_SUCCESS: "GET_NEWS_SUCCESS",
  GET_TAB: "GET_TAB",
  GET_PAGENR: "GET_PAGENR",
  GET_SEARCH: "GET_SEARCH",
  GET_BOOKMARKS: "GET_BOOKMARKS",
};
